version: '3.8'

services:

  redis-cache:
    image: redis:7-alpine
    container_name: local_redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: backend
    restart: no
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis-cache
volumes:
  redis_data: