spring.application.name=backend

server.port=8080


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false


spring.data.redis.host=redis-cache
spring.data.redis.port=6379


app.jwt.secretKey=KJt6yaCV+FS418hO5vHFbb4kC04pW5OPgZMM1p36NukFEje2dEO02/LEygYlXaPhs7Qqnm4L25F38uMRndxrdA==

# AWS S3 Configuration
aws.region=ap-southeast-1
aws.s3.bucket-name=ggdrive-local-storage
aws.credentials.access-key=${AWS_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_KEY}